### ISSUE TITLE
Unable to find library

### ISSUE THREAD

**Issue by klownie** [Detegr/cbqn-rs#2]
Systeme : archlinux in wgsl
kernel : Linux 5.15.167.4-microsoft-standard-WSL2

I'm unable to use the crate.
I followed the documentation and build the CBQN repository.
I also made the config.toml file :
```toml
[build]
rustflags = "-L /home/klownie/CBQN/BQN"
rustdocflags = "-L /home/klownie/CBQN/BQN"
```
when i run my programme it gives me :
```
/out" "-L" "/home/klownie/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/mnt/c/Users/klownie/Documents/Art/PortofolioWebsite/AxumHtmxAskamaPortofolioWebsite/target/debug/deps/AudrickConceptPortofolio-44de87ae44f83d80" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs"
  = note: rust-lld: error: unable to find library -lcbqn
          collect2: error: ld returned 1 exit status
```

I get the same output when i run it with 
LD_LIBRARY_PATH=/home/klownie/CBQN/BQN cargo r

**Comment by dzaima** [comment]
`/home/klownie/CBQN/BQN` looks potentially wrong - it should be the directory with a `libcbqn.so` file.

**Comment by klownie** [comment]
thanks i assumed that i needed to path to the file in upercase because of the documentation. 
my bad

**Comment by klownie** [comment]
i now have a new issue .
```
error: crate `shlex` required to be available in rlib format, but was not found in this form

error: could not compile `zstd-sys` (build script) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `aws-lc-sys` (build script) due to 1 previous error

```
should i create a new issue ?
