### ISSUE TITLE
 crate `shlex` required to be available in rlib format

### ISSUE THREAD

**Issue by klownie** [Detegr/cbqn-rs#3]
I'm making a website and thought it would be useful to use bqn in it.

the issue is that when i compile my code with the bqn lib i get :
```
error: crate `shlex` required to be available in rlib format, but was not found in this form

error: could not compile `zstd-sys` (build script) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `aws-lc-sys` (build script) due to 1 previous error

```

im running it with `LD_LIBRARY_PATH=/home/klownie/CBQN/libcbqn.so cargo r `

**Comment by klownie** [comment]
I did a cargo clean hoping it will fix it. 
Instead I am back to the old issue
```
  = note: rust-lld: error: unable to find library -lcbqn
          collect2: error: ld returned 1 exit status
```
even tho i folowed the configurations :
```toml
[build]
rustflags = "-L /home/klownie/CBQN/libcbqn.so"
rustdocflags = "-L /home/klownie/CBQN/libcbqn.so"
```

**Comment by Detegr** [comment]
`rustflags` and `rustdocflags` need to be pointed to the *directory* where `libcbqn.so` exists.
